import capeletImage from '@/assets/sujansky-capelet-aug2026.jpg';
import lynxReadingImage from '@/assets/sujansky-lynx-reading-aug2026.jpg';

export interface BlogPostImage {
  src: string;
  alt: string;
  caption?: string;
}

export interface BlogPostData {
  title: string;
  date: string;
  category: string;
  excerpt: string;
  likes: number;
  content: string[];
  images?: BlogPostImage[];
}

export const blogPosts: BlogPostData[] = [
  {
    title: 'Infectious Disease Update 8/18/2026',
    date: 'August 18, 2026',
    category: 'Infectious Disease Updates',
    excerpt: 'Covid trending up in the Bay Area, CDC approval of the first mRNA flu vaccine, the ongoing Legionnaires\' outbreak in New York, an escalating Ebola emergency, a 35-year high in measles cases, a widening cyclosporiasis outbreak, and other medical news.',
    likes: 0,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. I don\'t have much medical news to report - I think all the medical journals are relaxing a bit for the summer also...:)',
      'COVID-19',
      'General Information',
      '• Covid numbers are trending UP in the Bay Area as well as in much of the United States. Wastewater sampling has found increasing amounts of the virus since late June. Luckily, we have not yet seen a significant increase in hospitalizations.',
      '• As I mentioned previously, we are expected to have a "new" COVID vaccine this fall, to better reflect the type of SARS-Cov-2 virus circulating at this point in time. So, in general, I would wait for that to come out rather than getting the older vaccine right now....',
      'Other Infectious Diseases:',
      'FLU:',
      '• On August 5, the CDC approved the first influenza vaccine that uses mRNA technology (made by Moderna). Studies have found that it is about 27% more effective than a regular flu shot.',
      'LEGIONNAIRE\'S DISEASE:',
      '• Legionnaire\'s disease is a severe type of pneumonia caused by the bacterium "Legionella pneumophila," which is transmitted via aerosolized droplets originating from man-made water systems (water towers, hot/cold water systems, hot tubs, even hospital equipment).',
      '• Unfortunately, there is a large outbreak of Legionnaire\'s Disease in New York right now (Manhattan\'s Upper East Side). About 60 people have fallen ill and 15 people have been hospitalized.',
      '• Also, unfortunately, the City Health Department has not yet identified the water source associated with the outbreak.',
      'EBOLA:',
      '• The CDC has raised the emergency activation level for Ebola to it\'s most severe designation "reserved for critical emergencies." More than 1,200 people have been infected in Congo. The only other country with infections is Uganda.',
      '• Treatment consists of intense medical treatment in hospitals (ventilators and oxygen therapy, blood transfusions, medications to support the body). Unfortunately, the people who have gotten ill are also the most vulnerable people, as they live in remote regions of the world without much medical care.',
      '• Again, at this time, the disease has only been identified in the DRC and Uganda. Over 600 people have likely been infected and at least 139 people have died of the disease.',
      '• While vaccines have been developed in the past against the Ebola virus, this new variant (called "the Bundibugyo virus") does not yet have a vaccine that works for it.',
      'MEASLES:',
      '• In 2026, there have been more measles cases so far than at any time in the last 35 years. There have been more cases in 2026 so far than in all of 2025. In case you\'re wondering, that\'s 2,295 cases in the U.S. this year',
      'CYCLOSPORIASIS:',
      '• Cyclosporiasis is a food-borne parasitic disease that leads to abdominal cramps and explosive diarrhea. It is often associated with the consumption of fresh produce.',
      '• At this time, there is an outbreak with over 7000 of cases in 17 U.S. states. Overall, there have been 308 hospitalizations across 41 states but no deaths.',
      '• In early August, an additional 5 states were affected by the outbreak.',
      '• The CDC has associated the outbreak (or at least some of the disease transmission) to a single iceberg lettuce supplier that provides lettuce to Taco Bell restaurants. There may well be other sources of the disease also.',
      '• Luckily, at this time the Michigan Department of Health has told residents that they can go back to eating their salads and greens, as the outbreak seems to be slowing down.',
      'OTHER MEDICAL NEWS:',
      '• A new article in Comprehensive Physiology found that yoga helped with symptoms of Irritable Bowel Syndrome (IBS). The review article summarized 10 different articles and found that people who have IBS and do yoga have fewer gastrointestinal symptoms, as well as less depression and anxiety.',
      '• A study looking at more than 480,000 people found that the likelihood of dying of a heart attack or stroke was 39% lower in people who regularly climbed stairs...and their likelihood of dying of anything was 24% lower! Those numbers are huge! (American Journal of Cardiovascular Drugs). So, take the stairs if you are given the option...within reason!',
      '• Meanwhile, long-term exposure to pollution increased your risk of heart disease (Radiology). So pollution is bad for your heart as well as your lungs.',
      'About Dr. Sujansky\'s Life in These Times',
      'Well, I just finished knitting a "capelet" (think: little cape) to throw over the shoulders when it gets cool. Picture below. Although the pattern was not difficult, this easiness made me zone out a number of times while knitting and then I kept making mistakes...so I had to unravel my work more than once. Maybe this is a larger lesson: when you think that something is pretty mindless, you should probably pay more attention (I\'m thinking slicing tomatoes!) or you can end up in trouble... I\'m sure you can come up with your own examples.)',
      'I also attached a picture of my cat "Lynx" reading a book...all of the Sujansky family members love to read!',
      'Take care and enjoy the beautiful weather we are having. Life is good here.',
    ],
    images: [
      {
        src: capeletImage,
        alt: 'Dr. Sujansky wearing the purple capelet she knitted',
        caption: 'The finished capelet.',
      },
      {
        src: lynxReadingImage,
        alt: 'Lynx, a tabby cat, resting beside a copy of the book "Decoding Your Cat"',
        caption: 'Lynx, doing some light reading.',
      },
    ],
  },
  {
    title: 'Infectious Disease Update 7/14/2026',
    date: 'July 14, 2026',
    category: 'Infectious Disease Updates',
    excerpt: 'Latest updates on the new COVID-19 XFG variant vaccine, mRNA flu shot approval, Legionnaires\' disease outbreak in NYC, an escalating Ebola situation in Africa, ongoing measles spread, a cyclosporiasis outbreak, and other medical news.',
    likes: 0,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters.',
      'COVID-19',
      'General Information',
      '• There will be a new COVID-19 vaccine coming out in the fall that will target the XFG variant. This new-ish variant is better at avoiding our current immune system response to COVID-19 and currently makes up over half of new infections in the U.S.',
      '• A recent article published in JAMA Internal Medicine found that the COVID-19 vaccine REDUCED the risks of heart attacks and strokes by 40% and decreased the likelihood of dying by heart attacks and strokes by 60%! People older than 75 benefitted most. I just want to point this out because some people erroneously believe that the vaccine is somehow bad for your heart...',
      '• Similarly, not to beat a dead horse (what a horrible idiom!), but a recent article (Jama Network Open) found that the 2025/26 covid vaccine significantly reduced hospitalizations compared to people who did not get the vaccine last fall.',
      '• It turns out that getting the covid vaccine on the same day as getting the flu shot is not associated with more side effects (Annals of Internal Medicine).',
      'Other Infectious Diseases:',
      'FLU:',
      '• The FDA Advisory Committee on Vaccination had recommended approval of the new mRNA-based seasonal flu shot (made by Moderna). According to Moderna\'s website, this new mRNA vaccine has been 27% more effective than the current flu shot in reducing influenza in people older than 50.',
      'LEGIONNAIRE\'S DISEASE:',
      '• Legionnaire\'s disease is a severe type of pneumonia caused by the bacterium "Legionella pneumophila," which is transmitted via aerosolized droplets originating from man-made water systems (water towers, hot/cold water systems, hot tubs, even hospital equipment).',
      '• Unfortunately, there is a large outbreak of Legionnaire\'s Disease in New York right now (Manhattan\'s Upper East Side). About 60 people have fallen ill and 15 people have been hospitalized.',
      '• Also, unfortunately, the City Health Department has not yet identified the water source associated with the outbreak.',
      'HANTAVIRUS:',
      '• Great news! The World Health Organization has now said that the hantavirus outbreak is over!',
      'EBOLA:',
      '• The WHO has declared that the Ebola outbreak in Uganda and the Democratic Republic of Congo (DRC) is a "public health emergency of international concern." Nonetheless, it does NOT (thankfully!) meet the criteria of a pandemic emergency. Ebola disease starts with symptoms of a fever and flu-like symptoms, then goes on to severe nausea and vomiting. 33% to 50% of people go on to die, with bleeding occurring in different parts of the body. The virus is spread by direct contact with body fluids of people who are ill (urine, saliva, sweat, feces). So you can\'t get it by having someone cough or breathe on you. Also, luckily, only people who are feeling ill are contagious.',
      '• Unfortunately, some experts believe this outbreak will become the largest in all of "Ebola history" and possibly lead to the death of over 11,000 people unless more efforts are undertaken now to stem the tide of disease.',
      '• Treatment consists of intense medical treatment in hospitals (ventilators and oxygen therapy, blood transfusions, medications to support the body). Unfortunately, the people who have gotten ill are also the most vulnerable people, as they live in remote regions of the world without much medical care.',
      '• Again, at this time, the disease has only been identified in the DRC and Uganda. Over 600 people have likely been infected and at least 139 people have died of the disease.',
      '• While vaccines have been developed in the past against the Ebola virus, this new variant (called "the Bundibugyo virus") does not yet have a vaccine that works for it.',
      '• The CDC has raised the emergency activation level for Ebola to it\'s most severe designation "reserved for critical emergencies." More than 1,200 people have been infected in Congo. The only other country with infections is Uganda.',
      '• An American citizen working in the Democratic Republic of Congo has now tested positive for the virus and is in isolation in northeastern Congo.',
      'MEASLES:',
      '• Overall, in the United States, there have been 2030 cases of measles in 2026 so far. In all of 2025, there were 2,288 cases. Most of the cases are in children and teenagers and 92% of the people who fall ill were not vaccinated.',
      '• The state of Utah has now been battling a measles outbreak for an entire year! Over 680 have been sickened by measles in Utah in the last year and almost every county has been affected.',
      '• Although we are only half way through 2026, the number of measles cases is now close to the number seen in all of 2025 (2,288 cases in 2025), setting a new record by the end of the summer. Given these high numbers, the U.S. is now considered to be in a new phase of the epidemic, with new cases breaking out all over rather than being contained in isolated communities.',
      'CYCLOSPORIASIS:',
      '• Cyclosporiasis is a food-borne parasitic disease that leads to abdominal cramps and explosive diarrhea. It is often associated with the consumption of fresh produce.',
      '• At this time, there is an outbreak with thousands of cases in 17 U.S. states between May 1 and June 16. Most cases have been in Michigan, which has over 2,640 cases. I don\'t think there have been any cases in California for now. 15 people in Texas have been hospitalized with the disease.',
      '• Michigan health officials suspect that lettuce or other salad greens may be the source of the infection.',
      'OTHER MEDICAL NEWS:',
      '• A new sunscreen active ingredient ("bemotrizinol") was recently approved by the FDA for use in the United States. Bemotrizinol has been available in Europe for a long time, which is always nice for me to know! This ingredient is safe for adults as well as kids older than 6 months.',
      '• The United States death rate has fallen to it\'s lowest point in the country\'s history in 2025! Flu and pneumonia are now among the top 10 causes of death. The top two causes of death were heart disease and cancer.',
      '• We\'ve all heard about the overuse of smart phones by kids and teens being associated with mental health issues. Well, it seems that the youngsters are not the only ones at risk! A recent article in the journal JMIR Aging explained that excess use is also found among older folks and leads to depression. So avoid compulsively using the phone to scroll the news, watching videos, or playing games. And make sure you put lots of efforts into making and maintaining human being-based friendships!',
    ],
  },
  {
    title: 'Infectious Disease Update 4/6/2026',
    date: 'April 6, 2026',
    category: 'Infectious Disease Updates',
    excerpt: 'Here are the latest updates on infectious diseases affecting our community, including a new COVID variant, measles, polio, and other medical news.',
    likes: 0,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. New information will be in BOLD.',
      'COVID-19',
      'General Information',
      '• **An article in the Journal of Infectious Disease found that the updated mRNA COVID-19 vaccine of 2024/25 provided moderate protection against severe COVID-19, especially in seniors.**',
      '• **The Journal of Nutrition recently printed an article that Vitamin D3 did NOT seem to improve your infection if you got COVID-19, but it did reduce your likelihood of developing Long Covid.**',
      '• **There is a new SARS-Cov-2 variant of concern: it\'s called "Cicada" and is highly mutated compared to previous versions of the Covid virus. Although it is still less common in the U.S., numbers are increasing. And it represents up to 30% of the variants found in Europe. Stay tuned until we know more...**',
      '• **The antidepressant called "fluvoxamine" (but not the diabetes drug metformin!) was found to help with the fatigue associated with Long Covid. (Annals of Internal Medicine)**',
      'Other Infectious Diseases:',
      'FLU:',
      '• **Unfortunately, it seems like the most recent flu vaccine did not work as well as we were hoping: in fact, it was the least protective flu shot in the last 20 years! This was due to a new strain of influenza that caused people to get ill and that had not been included in the vaccine when it was formulated at the end of the last flu season.**',
      'RSV:',
      '• A recent study found that Pfizer\'s RSV vaccine is more than 90% effective in older adults in preventing the disease (Clinical Infectious Diseases).',
      'MEASLES:',
      '• **Before the measles vaccine became available in 1963, 3 to 4 million people in the U.S. were infected with measles each year, 48,000 ended up in the hospital, 400-500 died.**',
      '• There is NO scientific evidence that measles vaccines lead to autism, cancer, or heart disease.',
      '• **There are now over 1,362 cases of measles in the U.S. since the beginning of the year (96% of these were not fully vaccinated; 80% among kids and teens). I feel a little bit like when I was first reporting on the COVID pandemic and was giving weekly updates of ever-rising numbers of infected folks. That is getting a bit repetitive now...I think you get it that the situation is out of control...**',
      'POLIO:',
      '• **The CDC is now warning all international travelers to make sure their polio vaccinations are up to date. This follows a new "level 2" travel advisory based on multiple reports of polio outbreaks in parts of Africa, the Middle East, and Europe. Countries with outbreaks include Germany, Spain, the U.K., and Israel. Adults, who have completed the full vaccination series in the past, are recommended to have a single booster that should last them for the rest of their lives.**',
      'OTHER MEDICAL NEWS:',
      '• **A recent article in the Journal of the American College of Cardiology discussed diet and the prevention of heart disease. I think there has been too much hype made around the specific amounts of protein, fats, or carbohydrates that we should be consuming. Rather, we should concentrate on prior recommendations made by the Mediterranean diet, the DASH diet, and healthy plant-based eating index. For most people, a well-rounded diet of whole foods makes sense. I hold with Michael Pollan who recommended to "eat real food...not too much...mostly plants."**',
      '• **This should not come as a surprise to most of us, but a recent study looking at social media influencers promoting prescription medications found much misinformation and blurring of lines between personal testimony and paid promotions. And, of course, there is not much regulatory oversight of any of this. (JAMA Network Open). So, in case you were wondering, I don\'t get any money from any pharmaceutical company to promote any products.**',
      '• **I recently saw this article about living long and well and it summarized many of the things I believe in; check it out!**',
      'About Dr. Sujansky\'s Life in These Times',
      '**I recently saw the show "Dear San Francisco" and I loved it. It is an acrobatics show (along the lines of Cirque Du Soleil), but so much more than just gymnastics! It was warm and funny and just perfect. I highly recommend (see picture below!). Also, the theater is in the North Beach part of San Francisco, so you MUST have dinner first at one of the delicious Italian restaurants...and possibly gelato after the performance. Needless to say, that\'s what I did!**',
      '**Then, a few weeks ago, I did my (now annual) trip to the Baja Peninsula with a group of girlfriends. I also included some pictures of that below. It was "just what the doctor ordered" and included a massage, delicious food, shopping, and (perhaps) a margarita or two. Much as I love my husband and kids and love traveling with them, it is just a different experience traveling with a group of old (or should I say "long-time") friends who just get you. So this is another experience I highly recommend.**',
      '**Happy Spring to everyone! I recently read an article that said that autumn was a more popular season than spring, which I just don\'t get. I love spring and the promise of warmer days ahead. I hope all of you can enjoy the season like I do!**',
    ],
  },
  {
    title: 'Infectious Disease Update 2/24/26',
    date: 'February 24, 2026',
    category: 'Infectious Disease Updates',
    excerpt: 'Here are the latest updates on infectious diseases affecting our community, plus a few other medical notes of interest.',
    likes: 51,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. New information will be in BOLD.',
      'COVID-19',
      'General Information',
      'â€¢ The CDC released data showing that "COVID vaccine administered last fall sharply decreased the risk of emergency department and urgent care visits in children." (Morbidity and Mortality Weekly Report). The risk decreased by 76% in kinds under age 4, and by 56% for kids aged 5 to 17.',
      'â€¢ **I know that it sometimes seems that the COVID-19 vaccines don\'t work, as we seem to get infected despite being vaccinated! Well, a new study (Open Forum Infectious Diseases) found that being vaccinated decreased your likelihood of ending up in urgent care or in the emergency department. This data is from September, 2024 to April, 2025. Similarly, an article in JAMA Network Open showed that vaccines protected you against severe outcomes of COVID-19, especially in seniors. Vaccinated people were 73% less likely to end up on a ventilator for infection with the virus if they had been vaccinated.**',
      'â€¢ **Covid-19 is certainly much less of a killer than it was in 2020 or 2021. Thank goodness for that! At the same time, in the 2023-2024 period, 879,000 people were hospitalized with the infection and more than 100,000 people died. More than 80% of the people who died and 67% of the people who were hospitalized were 65 or older. (Jama Internal Medicine).**',
      'Other Infectious Diseases:',
      'FLU:',
      'â€¢ Although the current flu vaccines was not formulated to include the new strain H3N2, it should still lessen the severity of influenza if you do get it.',
      'â€¢ **Unfortunately, the number of kids dying of influenza has steadily doubled each week in recent past. At this time, 52 kids were reported to the CDC as having died of influenza this season. Overall, 9,300 people have died of influenza overall and 230,000 people have been hospitalized, according to the CDC. On many measures, this is the worst flu season we have seen in 15 years.**',
      'RSV:',
      'â€¢ A recent study found that Pfizer\'s RSV vaccine is more than 90% effective in older adults in preventing the disease (Clinical Infectious Diseases).',
      'MEASLES:',
      'â€¢ **Before the measles vaccine became available in 1963, 3 to 4 million people in the U.S. were infected with measles each year, 48,000 ended up in the hospital, 400-500 died.**',
      'â€¢ There is NO scientific evidence that measles vaccines lead to autism, cancer, or heart disease.',
      'â€¢ We are continuing to see more measles in the U.S. There were over 2000 recorded cases in 2025, which is the highest level in over 30 years. In 2024, the U.S. had only 285 cases. Of those who were sickened by the disease, 93% were unvaccinated or had unknown vaccination status. California had only 25 cases overall.',
      'â€¢ South Carolina currently has one of the worst outbreaks in the nation and has sickened over **973 people. This is more people than those who were found to have measles in the recent outbreak in Texas. Of those infected, the vast majority were not fully vaccinated or had unknown vaccination status.**',
      'â€¢ **26 other states are seeing measles cases also.**',
      'â€¢ **Sadly, California also has an outbreak of measles: a number of different counties are involved (including San Mateo). At this time, there have been 17 cases since the beginning of the year (2 months!). As a comparison, in 2023 there were 4 cases; in 2024, 15 cases; in 2025: 25 cases....**',
      'OTHER MEDICAL NEWS:',
      'â€¢ **Good news! The U.S. life expectancy is now higher than ever in the past at 79 years! This is especially wonderful, as it had dropped to 76.5 during the pandemic. We\'re back! (The bad news: the U.S. still rank lower than dozens of other countries...).**',
      'â€¢ **A new study shows that gout medications can help also decrease your likelihood of heart attacks and strokes - in addition to reducing gout-related joint damage (JAMA Internal Medicine).**',
      'â€¢ **OK, so BEWARE!: a recent article (JAMA Network Open) looked at online health information videos produced by "health professionals" and found that fewer than 20% had high quality back up of their medical claims. That\'s sad. Even worse, there are plenty of social media posts seemingly by respected doctors that are fake and generated by AI! Who can you trust these days? I recommend you stick with the information from nerds who may not be flashy but can substantiate their opinions.**',
      'â€¢ **A recent article in Nature Medicine looked at the health advice rendered by A.I. chatbots. It seems the chatbots were no better than Google, which is known to have flawed health information. So, please!, feel free to contact me with questions. Chatbots are NOT ready for prime time medical care!**',
      'â€¢ **I was happy to see that small changes in lifestyle can have a big impact on health (eClinical Medicine): even 5 extra minutes of exercise a day can increase your lifespan...and even more so if we incorporate positive changes in sleep and nutrition.**',
      'â€¢ **Finally, a study published in Neurology found that lifelong learning (writing, reading, going to museums) can decrease your likelihood of developing Alzheimer\'s in your later years.**',
      'About Dr. Sujansky\'s Life in These Times',
      '**All is well on the home front. I finished a new knitting project (see below) and I\'m now starting a shawl for my sister. For me, learning how to knit was one of the best things that came out of the pandemic.**',
      '**I spent the President\'s Day weekend in Florida, enjoying some quality time with my sister and mother...and watching a lot of Olympics! That was fun! I have so much appreciation for the athletes, every one of who has put so much time and effort and pain in perfecting their craft. Can you just imagine how many sacrifices they had to make to get as far as they did? I tip my hat to them!**',
    ],
  },
  {
    title: 'Infectious Disease Update 1/13/2026',
    date: 'January 20, 2026',
    category: 'Infectious Disease Updates',
    excerpt: 'Here are some updates on various infectious diseases that are affecting our community.',
    likes: 47,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. New information will be in BOLD.',
      'COVID-19',
      'General Information',
      '• At this time, the new guidelines recommend vaccinating for COVID in the spring.',
      '• The CDC released data showing that "COVID vaccine administered last fall sharply decreased the risk of emergency department and urgent care visits in children." (Morbidity and Mortality Weekly Report). The risk decreased by 76% in kinds under age 4, and by 56% for kids aged 5 to 17.',
      '• **Covid cases nationwide are increasing, though we have not noted this trend in Northern and Central California (yet).**',
      'Other Infectious Diseases:',
      'FLU:',
      '• **The U.S. is seeing a sharp increase of flu cases now, thought to be brought on by a new flu virus strain "H3N2." The holidays and associated holiday travel likely contributed to this uptick. This increase in numbers is likely not to improve until mid February. At this time, the CDC estimates that "there have been at least 4.6 million flu-related illnesses, at least 49,000 hospitalizations, and 1,900 deaths" during the current flu season. And, unfortunately, we are seeing much more flu in the Bay Area in recent weeks.**',
      '• **The United Kingdom is also seeing a lot of flu activity, with people between the ages of 5 and 24 being most affected. Hospitalizations have doubled in the last week and are setting new records.**',
      '• **Luckily, there are some signs that the flu outbreak may be declining already. It is too early to say for sure, so stay tuned.**',
      '• **Kids are particularly hard hit: the number of children and teenagers hospitalized with influenza this season is the second highest in 15 years.**',
      '• Although the current flu vaccines was not formulated to include the new strain H3N2, it should still lessen the severity of influenza if you do get it.',
      'RSV:',
      '• A recent study found that Pfizer\'s RSV vaccine is more than 90% effective in older adults in preventing the disease (Clinical Infectious Diseases).',
      '• **Unfortunately, it seems like RSV infections throughout the country (and also in our neighborhood) are increasing.**',
      'MEASLES:',
      '• **Before the measles vaccine became available in 1963, 3 to 4 million people in the U.S. were infected with measles each year, 48,000 ended up in the hospital, 400-500 died.**',
      '• There is NO scientific evidence that measles vaccines lead to autism, cancer, or heart disease.',
      '• **We are continuing to see more measles in the U.S. There were over 2000 recorded cases in 2025, which is the highest level in over 30 years. In 2024, the U.S. had only 285 cases. Of those who were sickened by the disease, 93% were unvaccinated or had unknown vaccination status. California had only 25 cases overall.**',
      '• **South Carolina currently has one of the worst outbreaks in the nation and has sickened over 434 people, an increase of 124 cases in the last week alone.**',
      '• **Two recent studies (Morbidity and Mortality Weekly Report) show that wastewater testing can predict measles outbreaks days to months before they occur. This could allow health officials to anticipate cases and make sure unvaccinated people receive last-minute protective vaccinations. Unfortunately, this national wastewater surveillance system is threated by budget cuts...**',
      'OTHER MEDICAL NEWS:',
      '• **On December 30, CMS issued a letter that removed the reporting requirement for four major pediatric and prenatal immunizations. This makes it much more difficult to see if a community has adequate "herd immunity" to protect those babies that are not yet vaccinated for certain diseases or those people who can\'t be vaccinated for medical reasons.**',
      '• **A new study published in the Cochrane Database to Systemic Reviews found that exercise was just as helpful in treating depression as therapy or medications are....now, I\'m NOT recommending anyone stop therapy or stop their medications, but I will urge everyone with symptoms of depression to crank up their exercise...to whatever extent they can!**',
      'About Dr. Sujansky\'s Life in These Times',
      '**Happy belated New Year to all of you! I hope you had wonderful holidays and are ready to take on the new year with gusto! I am attaching a picture of a rose that I just took the other day, which explains one reason that I love living in this part of the world.**',
      '**My family spent a week in late December in Tahoe, skiing. We were lucky in Tahoe, as it snowed heavily just the week prior to our trip. Skiing was fun, but I have to admit that I sent the rest of my family out on several days while I sat alone by the fire and read or knitted. I also went snow-shoeing one day. Both my sons were home for Christmas, which we hadn\'t had for some years. It was soooo nice!**',
    ],
  },
  {
    title: 'Infectious Disease update 12/16/25',
    date: 'December 16, 2025',
    category: 'Infectious Disease Updates',
    excerpt: 'Here are the latest updates on COVID-19 and various other infectious diseases affecting our community and our country.',
    likes: 44,
    content: [
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. New information will be in BOLD.',
      'COVID-19',
      'General Information',
      '• **Another study has found that COVID vaccinations (especially in people who also had a history of COVID-19 infection itself) is 81% - 92% effective in preventing future LONG COVID (Clinical Infectious Diseases).**',
      '• **New research shows that people with Long COVID have markedly increased inflammatory markers compared to people who have recovered from acute COVID-19 infections normally (Nature Immunology). Past studies have similarly showed that Long COVID seems to be associated with an immune system that is turned on by the acute infection and then is not turned off.**',
      '• **COVID levels are continuing to decrease in Northern California as well as the Central Coast.**',
      '• **The Infectious Disease Society of America recently recommended that people who have a compromised immune system, as well as those living with/ around immunocompromised people, should be vaccinated for COVID-19.**',
      '• **At this time, the new guidelines recommend vaccinating for COVID in the spring.**',
      '• **Public health researchers in Norway and Sweden did NOT find an associated of the COVID-19 vaccine and the incidence of muscle inflammation. Also, the WHO vaccine safety committee did not find any link between vaccines and autism spectrum disorder.**',
      '• **The CDC released data showing that "COVID vaccine administered last fall sharply decreased the risk of emergency department and urgent care visits in children." (Morbidity and Mortality Weekly Report). The risk decreased by 76% in kinds under age 4, and by 56% for kids aged 5 to 17.**',
      '• **Similarly, a recent report in the New England Journal of Medicine found that the flu, RSV, and Covid vaccines were safe and effective and led to significant decreases in hospitalizations.**',
      '• **The above notwithstanding, the FDA plans on adding a "black box warning" on COVID-19 vaccines, warning of the life-threatening or disabling reactions that must be considered. It was left unclear if such warnings related to the mRNA vaccines or all COVID vaccines. I am not aware of that the FDA provided information as to what data prompted this new black box warning.**',
      'Other Infectious Diseases:',
      'FLU:',
      '• Japan has had an early influenza season this year and has just announced that they are in the middle of a nationwide flu epidemic. **This early and severe flu outbreak is continuing now.**',
      '• **South Korea and the United Kingdom are also seeing much flu activity, thought to be brought on by a new flu virus strain "H3N2." In fact, the United Health Service in the UK is predicting that this will be the worst flu season in a decade. Children and young adults seem to be particularly effected in the UK.**',
      '• **Australia had its worst flu season on record this year.**',
      '• **Last year\'s flu season was the worst in a long while and led to the highest number of hospitalizations since 2010/2011.**',
      '• **Although the current flu vaccines was not formulated to include the new strain H3N2, it should still lessen the severity of influenza if you do get it.**',
      '• **In the United States, we are seeing flu activity up by at least 7% just in the last week. So far, there have been almost 2 million people sick,19,000 people hospitalized, and 750 people who have died this season of the flu virus.**',
      '• **Nonetheless, we are NOT seeing a lot of influenza in Northern California at this time**',
      'RSV:',
      '• There has been a marked recent increase in babies and children hospitalized for RSV.',
      '• **A recent study found that Pfizer\'s RSV vaccine is more than 90% effective in older adults in preventing the disease (Clinical Infectious Diseases).**',
      '• **RSV levels are the lowest they have been in the last 3 years, if we look at the Sutter system only.**',
      'NOROVIRUS:',
      '• We have discussed norovirus in the past: it leads to severe nausea/ vomiting and diarrhea and is often seen on cruise ships.',
      '• Luckily, scientists are developing a norovirus vaccine, so hopefully we can cruise with more comfort in the future!',
      '• **Norovirus cases continue to increase in the U.S. this year and, indeed, have doubled over the last few months.**',
      'MEASLES:',
      '• **Before the measles vaccine became available in 1963, 3 to 4 million people in the U.S. were infected with measles each year, 48,000 ended up in the hospital, 400-500 died.**',
      '• There is NO scientific evidence that measles vaccines lead to autism, cancer, or heart disease.',
      '• **We are continuing to see more measles in the U.S. At this time, there are about 1,700 people who were infected in 2025. By comparison, there were 285 cases in 2024 and 13 cases in 2020. South Carolina, Utah, and Arizona are seeing outbreaks at this time.**',
      '• **Canada has now lost its status of having eliminated measles. The U.S. is on track to lose its measles-elimination status in short order.**',
      'OTHER MEDICAL NEWS:',
      '• **Some months ago, I noted that the shingles vaccine was associated with a decreased likelihood of developing dementia. Well, a recent follow up study (Cell) confirmed this finding and showed that the vaccine decreased your chance of developing dementia by 20%! Even if you have dementia already, getting the vaccine may keep you from dying of dementia.**',
      '• **Yet another study in BMC Medicine found that the antioxidants found in tea, coffee, cocoa, nuts, whole grains, and olive oil are great for your heart. Bring on the dark chocolate!**',
      'About Dr. Sujansky\'s Life in These Times',
      '**And, just like that, the Holidays are upon us!**',
      '**I have completed my annual cookie baking Sunday with two old friends from college, a tradition we have had for the last 30 years or so.** We are planning on ice skating in San Francisco this week. We even went curling (so much fun and really funny-looking too!) last week. The tree is trimmed and my boys will soon both be home for a few weeks. Now, that is reason for gratitude!',
      '**I wish all of you some joy, rest, and peace in this time and hope that 2026 blesses all of us with the same.**',
    ],
  },
  {
    title: 'Infectious Disease Update 11/4/2025',
    date: 'November 4, 2025',
    category: 'Infectious Disease Updates',
    excerpt: 'Here are the latest updates on a variety of infectious diseases as well as some other medical topics of interest.',
    likes: 39,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. New information will be in BOLD.',
      'GENERAL:',
      '• **We all know that all sorts of immunizations have come to be viewed with suspicion in recent years. So I was happy to see a new study in the New England Journal of Medicine that looked over 511 (!!) studies reviewing the safety of vaccinations. The conclusion? "Immunizations against COVID-19, respiratory syncytial virus (RSV), and influenza effectively and safely reduced the risk of severe outcomes in people of all ages." In particular, in the 2025/26 season, COVID vaccination reduced hospitalizations by 46% to 50% (and actually 65% in kids!).**',
      'COVID-19',
      'General Information',
      '• **Children who were infected with the COVID-19 virus on two occasions were also twice as likely to develop Long Covid (Lancet).**',
      '• **A study looking at a total of 1.2 million women found that COVID vaccination during pregnancy helped protect both the mother and the child without any increased risk to either. Rates of stillbirth and preterm birth decreased (Study presented at the American Academy of Pediatrics).**',
      '• **Fingers crossed, but the wastewater levels of the COVID virus (SARS-Cov-2) are decreasing both nationwide and in California!**',
      '• **A recent article (New England Journal of Medicine) found that the 2024/ 25 COVID vaccine continued to provide benefits...even in this day and age when COVID-19 is often no longer considered dangerous by some: the vaccine reduced emergency room visits by almost 30%, reduced hospitalization by almost 40%, and reduced death by 64%.**',
      '• **I know that many people are frightened by rumors of adverse effects associated with the COVID vaccines. A recent article (JAMA Internal Medicine) looked at the babies born from a mother who had received the COVID vaccination in the first trimester: there were NO increased birth defects noted in the babies.**',
      '• **Meanwhile, an article in Obstetrics and Gynecology found that babies born of mothers who had COVID-19 during the pregnancy, were MORE likely tot develop autism down the road.**',
      'Other Infectious Diseases:',
      'FLU:',
      '• We often look to Australia, whose flu season is just now ending, as a predictor of how bad our season will be. Unfortunately, Australia had a severe flu season in 2025. Luckily, the vaccine seemed to be a good match for the circulating virus.',
      '• **We do have the flu shot in our office, so you are welcome to stop by and get a shot.**',
      '• **Japan has had an early influenza season this year and has just announced that they are in the middle of a nationwide flu epidemic.**',
      '• **We do not have any accurate numbers for the number of flu cases in the U.S.: the CDC is not reporting anything in the setting of the budget impasse.**',
      '• **Sutter is noting 40-60 cases of influenza every week at this time.**',
      '• **Looking at the southern hemisphere, that is just finishing up its annual flu season, experts found that vaccination reduced the likelihood of coming to medical attention due to influenza by 50%.**',
      '• **President Trump\'s physician reported that the president also received a flu and Covid booster in early October of this year.**',
      '• **Yet another article (Journal of the American Heart Association) found that flu (and COVID-19) infections increase your risk of heart attacks and strokes by 500-600%.**',
      'RSV:',
      '• **There has been a marked recent increase in babies and children hospitalized for RSV.**',
      'BIRD FLU:',
      '• **Luckily, we have not heard much about the bird flu for many months. Unfortunately, that may now change: with the changes of seasons, water fowl are again migrating. As a consequence, livestock are getting infected. In the last month alone, over 4 million poultry birds have had to be culled, due to bird flu infections. Stay tuned...**',
      'NOROVIRUS:',
      '• **We have discussed norovirus in the past: it leads to severe nausea/ vomiting and diarrhea and is often seen on cruise ships.**',
      '• **Luckily, scientists are developing a norovirus vaccine, so hopefully we can cruise with more comfort in the future!**',
      'MEASLES:',
      '• Measles was thought to have been eradicated in the U.S. in 2000. Unfortunately, vaccination rates have since fallen, leaving communities very vulnerable to the highly infectious disease. Last year, there were 285 cases of measles reported in the U.S.',
      '• Before the measles vaccine became available in 1963, **3 to 4 million people in the U.S. were infected with measles each year, 48,000 ended up in the hospital, 400-500 died.**',
      '• There is NO scientific evidence that measles vaccines lead to autism, cancer, or heart disease.',
      '• The **Texas measles outbreak is now over! Unfortunately, many other smaller outbreaks are occurring all over the U.S.: there are an average of 27 new cases reported each week since the end of August. At this time, there have been more than 1,600 cases since the beginning of the year. This is the highest number (by a lot!) since measles was declared eradicated 25 years ago. Also, there are 30-times more measles cases compared to 2024.**',
      '• Right now, there is an **outbreak along the border between Utah and Arizona that is the third largest for 2025. More than 100 people have fallen sick from measles here. As in the Texas outbreak, the affected communities had a large number of people who had not been vaccinated with the measles, mumps, and rubella vaccine.**',
      '• There is a **new anti-viral medication against measles in development. It has the catchy name of "NV-387." It is currently available for emergency use only.**',
      'OTHER MEDICAL NEWS:',
      '• **JAMA Network Open: a recent article found that older adults who tried acupuncture for their chronic low back pain found significant relief.**',
      '• **A recent study (JAMA Psychiatry) found that people who drink soft drinks are more likely to develop depression. It is thought that the soft drinks lead to changes in your gut bacteria (microbiome) that bring on depressive symptoms. Women seem to be more affected than men.**',
      '• **Good news: as you may remember, during the pandemic, life expectancy had (understandably) dropped in the U.S. However, starting in 2023, life expectancy is back to pre-pandemic levels. Currently, the average life expectancy for women is 76.3 years, and for men, it\'s 71.5 years.**',
      '• **We all know that prunes and prune juice can help treat and prevent constipation. Well, new dietary guidelines also note that kiwi, rye bread, and high-mineral waters can help with chronic constipation. (Journal of Human Nutrition and Dietetics and Neurogastroenterology &Motility)**',
      '• **A study published in British Journal of Sports Medicine found that taking at least 4000 steps once or twice a week was associated with a 26% lower risk of death in women 62 or older. And for older women who took over 4000 daily steps 3 times per week, mortality went down by 40%! Along similar lines, an article published in Nature Medicine found that people with early Alzheimer\'s can slow their cognitive decline by 3 years by walking 3,000 to 5,000 steps a day...and by 7 years by walking 5,000 to 7,500 steps daily!**',
      'About Dr. Sujansky\'s Life in These Times',
      '**I had a great October! In the middle of the month, I went to a medical conference on the East Coast...and took the opportunity of visiting my son in Maine while I was on that side of the continent. It was so good to see him and the weather was fabulous! It turns out that I was there at the perfect time for "leaf peeping," the activity of taking in the beautiful change of color brought on by autumn. On, yeah, and the conference was interesting also :)!**',
      '**Halloween was fun. As I may have mentioned in the past, we are in a neighborhood street that gets lots of trick-or-treaters. I counted, and this year we got 432! So fun to see all of the costumes! And I really enjoy dressing up myself...**',
      '**That\'s all I\'ve got for today!**',
    ],
  },
  {
    title: 'Infectious Disease Update 9/30/2025',
    date: 'September 30, 2025',
    category: 'Infectious Disease Updates',
    excerpt: 'Here is some of the latest information about various infectious diseases and a few other medical topics.',
    likes: 35,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. New information will be in BOLD.',
      'GENERAL:',
      'COVID-19',
      'General Information',
      '• A new study (JAMA Health Forum) estimated that, worldwide, the COVID-19 vaccination saved 2.5 MILLIONS of lives, especially in older adults.',
      '• On August 27, the FDA approved the updated COVID-19 vaccines for the fall. Two things are noteworthy: there now is a new "version" of the covid shot that will better address the circulating variants (much like there is a new flu shot every year). This time, however, the vaccines are ONLY recommended for people over 65, or younger patients that have underlying medical conditions that make them more vulnerable, and healthy kids (with consultation of the doctor). These regulations are quite a bit more restrictive than in the past.',
      '• In addition, the newly-appointed ACIP advisory committee ("Advisory Committee on Immunization Practices") recommended that people over 65 only be vaccinated against COVID-19 "after discussions with their health care provider." So, for the record, if you are over 65 and are my patient: I RECOMMEND YOU GET VACCINATED FOR COVID-19.',
      '• America\'s Health Insurance Plans, however, announced that they would continue current coverage despite the changes announced by ACIP and CDC, at least through the end of 2026.',
      '• The wave of increased COVID infections continues, though we have not seen a lot of very sick people and mortality is low. National waste water levels of virus are high. California is in the "very high" stage.',
      '• Now, this is interesting: the over-the-counter nose spray "azelastine," which is usually used to treat allergies, may also help in preventing COVID infections! A growing amount of research indicates that azelastine may help prevent a number of viral infections, including influenza, RSV, as well as SARS-Cov-2 (the virus that causes COVID-19). People may be able to use this to prevent COVID in themselves, if they are anticipating an exposure to the virus (JAMA Internal Medicine).',
      '• You might recall that there have been various reports in the past that indicate that the diabetes drug metformin may be helpful in combatting Covid-19. Well, a new study (Clinical Infectious Diseases) found that metformin may also reduce your risk of developing Long Covid if you are overweight and infected with the virus.',
      'Other Infectious Diseases:',
      'FLU:',
      '• We often look to Australia, whose flu season is just now ending, as a predictor of how bad our season will be. Unfortunately, Australia had a severe flu season in 2025. Luckily, the vaccine seemed to be a good match for the circulating virus.',
      '• Children (especially) who are infected with influenza can rarely develop a nasty brain infection called "acute necrotizing encephalopathy." Unfortunately, the number of kids with this in the 2024/25 flu season went up - though only 109 children had it in the United States. Vaccination helps protect from this deadly consequence.',
      '• I recommend getting the flu shot in October and early November. We do have the flu shot in our office, so you are welcome to stop by and get a shot.',
      'MEASLES:',
      '• Measles is a highly contagious disease. Every person sick with measles can transmit the virus to 12-16 unvaccinated people. Just standing next to someone with measles (as in an international airport) can be enough to get you sick.',
      '• Measles was thought to have been eradicated in the U.S. in 2000. Unfortunately, vaccination rates have since fallen, leaving communities very vulnerable to the highly infectious disease. Last year, there were 285 cases of measles reported in the U.S.',
      '• Before the measles vaccine became available in 1963, 3 to 4 million people in the U.S. were infected with measles each year, 48,000 ended up in the hospital, 400-500 died.',
      '• At this time, 1,514 people have developed measles in the U.S. in 2025. Recent new cases are related to travel as well as fresh outbreaks in Utah and Arizona.',
      '• The new Advisory Committee on Immunization Practices (ACIP) recommended to the CDC that the MMRV vaccine against measles not be given to kids until age 4. This recommendation notwithstanding, the vaccines should continue to be covered by insurance for children as young as 12 months.',
      '• Most children who are sick enough to be hospitalized with measles are between 11 months and 3 years old. This is one reason I would not recommend waiting until a child is 5 or older before vaccinating them.',
      '• LA county announced that a child had died of a brain infection due to measles infection. This brain infection (known as SSPE, "subacute sclerosing panencephalitis") is most common in kids under 5, and particularly in kids under 2. About one person in 1,400 who contracts measles goes on to have SSPE.',
      '• A recent study done in collaboration with Stanford University has found that the United States no longer has enough people vaccinated against infectious diseases such as measles to prevent outbreaks. As noted in the past, there needs to be a "critical mass" of people vaccinated in order to prevent outbreaks. For example, in Mohave County, Arizona there have been 42 confirmed cases of measles. And as of last year, not a single kindergarten school class in the county had enough kids vaccinated to provide a herd immunity for measles.',
      '• There is NO scientific evidence that measles vaccines lead to autism, cancer, or heart disease.',
      'OTHER MEDICAL NEWS:',
      '• For people who have had colon cancer themselves, taking daily aspirin can cut the likelihood of the cancer coming back by 50% (New England Journal of Medicine).',
      '• Exercising muscles produce substances that seem to suppress breast cancer cells (Breast Cancer Research and Treatment). In this study, a single session of exercise, led to increased cancer-fighting molecules in the blood.',
      '• As you may imagine, climate change will lead to many changes in our country\'s (and the world\'s!) health problems. We have mentioned the increase of mosquito-borne infections in the past. However, predictions published in the journal Nature suggest that wildfire smoke will do the most harm to our health.',
      '• The DEA and other federal agencies will be offering thein bi-annual "National Prescription Drug Take Back Day" on October 25, 2025. This allows for people to return unused and unwanted medications from their homes. Please look at their website at:',
      'https://www.dea.gov/takebackday',
      'About Dr. Sujansky\'s Life in These Times',
      'We just returned from a biking trip in Southern France. My gosh, was that fun! Biking all day through the beautiful French countryside....and eating all those delicious pastries, croissants, and cheese at most every meal. It was perfect! Moreover, we went with a group of friends, so great conversations and camaraderie were the order of the day. And, let me tell you, it was so nice to be distracted by that conversation and camaraderie when I was biking uphill and my legs were feeling tired! Also, who knew that there were so many 1000-year-old churches in every small village, each one more gorgeous than the last!',
      'Fall is here. As much as I love summer, I am also enjoying the changing color of leaves and the slight briskness in the air. Plus, my cup of coffee just tastes better when the weather is a bit cool. Change is good. On to the next adventure!',
    ],
  },
  {
    title: 'Infectious Disease Update 8/26/2025',
    date: 'August 26, 2025',
    category: 'Infectious Disease Updates',
    excerpt: 'Here are the latest updates on some infectious disease topics that may be of interest to you.',
    likes: 32,
    content: [
      'Update on Infectious Disease Threats: What You Need to Know',
      'Information about various infectious diseases is constantly evolving. I am hoping to summarize some of that in these newsletters. New information will be in BOLD.',
      'GENERAL:',
      'COVID-19',
      'General Information',
      '• COVID cases are risking again, due to a new strain "NB.1.8.1." It is also affectionately known as "Nimbus." Hospitalizations are going up also, as we have seen in parts of Asia in particular. And it seems that this particular variant is quite contagious also, though luckily no more dangerous than previous strains.',
      '• This new variant has also gathered the moniker "razor blade throat," which does not sound good!',
      '• The current vaccines should work as well against the current variants as they did against the previous ones.',
      '• Luckily, national hospitalizations for COVID-19 are at the lowest level since the pandemic started. Nonetheless, hospitalizations are rising again and California wastewater levels are going up also.',
      '• Also, we are seeing more COVID-19 in the Sutter system.',
      '• Utah, Texas, Nevada, Alaska, Hawaii have the highest amount of virus in their wastewater, and so are considered to be at highest risk.',
      '• I recommend you get another booster for the COVID now as I have seen lots of my patients fall sick with COVID-19 in recent weeks.',
      '• The updated COVID-19 vaccines from 2023/ 24 were able to effectively prevent COVID-19: getting a shot led to a 24% lower risk of going to the emergency department, a 29% lower risk of being hospitalized, and a 48% lower risk of ending up in the ICU! This protection lasted up to 300 days after vaccination, though you were most protected in the first 2 months after vaccination. (JAMA Network Open).',
      '• Scientists have found a new medication to treat the post-Covid multisystem inflammatory disease of children (MIS-C). The medication, larazotide, led to a 90% improvement of GI symptoms and many more kids who received the drug were able to resume their usual activities within 3 weeks. (Science Translational Medicine)',
      '• A new study (JAMA Health Forum) estimated that, worldwide, the COVID-19 vaccination saved 2.5 MILLIONS of lives, especially in older adults.',
      '• COVID-19 infection is associated with an accelerated aging of arteries, raising the concern that- even when patients recover- people will be more likely to have heart attacks and strokes (European Heart Journal).',
      'Other Infectious Diseases:',
      'Norovirus:',
      '• Norovirus is an extremely contagious virus that causes severe diarrhea, nausea, and vomiting.',
      '• Alcohol hand sanitizer does NOT kill the norovirus....but good old-fashioned soap and water does!',
      '• Since January 1, 2025, 16 cruise ship outbreaks of gastrointestinal illnesses have been reported and at least 12 of these were due to norovirus. In all of 2024, there were 18 outbreaks (15 with norovirus).',
      'FLU:',
      '• A study from JAMA found that in the last two years, there were 41 cases of severe brain disease (acute necrotizing encephalopathy) in children with influenza. Most of these occurred in previously healthy kids and 11 kids died. All but one of the kids had NOT been vaccinated.',
      'MEASLES:',
      '• Measles is a highly contagious disease. Every person sick with measles can transmit the virus to 12-16 unvaccinated people. Just standing next to someone with measles (as in an international airport) can be enough to get you sick.',
      '• Measles was thought to have been eradicated in the U.S. in 2000. Unfortunately, vaccination rates have since fallen, leaving communities very vulnerable to the highly infectious disease. Last year, there were 285 cases of measles reported in the U.S.',
      '• Before the measles vaccine became available in 1963, 3 to 4 million people in the U.S. were infected with measles each year, 48,000 ended up in the hospital, 400-500 died.',
      '• Complications associated with measles include pneumonia, brain infections, vulnerability to future infections of multiple kinds, hearing loss, and pregnancy complications.',
      '• The death rates associated with measles is usually 2 per 1000.',
      '• Currently, the measles outbreak in Texas is officially over! There have not been any new cases in the last 42 days! The final count of people who fell sick was 762 (about 100 people ended up in the hospital). Unfortunately, the outbreak is ongoing in New Mexico, where new cases are still popping up. At this time, there are 1,333 people who are known to be infected nationwide. 13% of people with known measles have been hospitalized. Children less than 5 with measles have a hospitalization rate of 23%. Three people (including 2 otherwise healthy children) have died. 92% of the cases were in people who were either unvaccinated or had an unknown vaccination status. 3% were fully vaccinated. Most cases are in children aged 5 to 17. Cases in the U.S. are more than 4.5 times higher than in all of 2024.',
      '• Meanwhile, Canada also has a very large outbreak of measles: there, over 4,000 cases have been reported.',
      '• On August 15, the Pan American Health Organization also reported an increase of measles in the Americas. 10,139 cases and 18 deaths have been confirmed among 10 countries; this is 34-times as many cases as one year ago.',
      '• There is NO scientific evidence that measles vaccines lead to autism, cancer, or heart disease.',
      'Diseases Transmitted By Mosquitoes',
      '• We are seeing a significant increase of mosquito-related infections in recent years, a likely consequence of global warming and the associated increase in areas in which mosquitoes live and breed. Also: some details: The Aedes mosquito bites you during the daytime. It transmits a number of diseases, including dengue, Zika, yellow fever, and chikungunya. Scientists are concerned that this mosquito may soon become endemic in the United States.',
      '• Here are some of the diseases of which you should be aware:',
      '• - Chikungunya fever: 3 to 7 days after being bitten and infected by the mosquito, you develop fever with shaking chills, headache, muscle pain, and severe joint pain with swelling and a rash that covers much of your body. Symptoms improve within 5 to 14 days, but can last for months. Some people go on to have chronic inflammatory arthritis.',
      '• - West Nile Virus (WNV): we typically see this in California from June 1 to November 1. So far, there have been 14 cases in California this year. This can lead to brain inflammation.',
      '• - I think this is enough information on mosquito-borne diseases for one newsletter....kinda scary and depressing!',
      'OTHER MEDICAL NEWS:',
      '• It seems that a diet rich in eggs (especially egg yolk!) may reduce your risk of Alzheimer\'s Disease! After studying over 1,000 U.S. adults, researchers found that those who consumed at least one egg per week had a 47% reduced risk of the disease. The benefit may be linked to the egg yolk nutrient "choline," that helps support memory and brain function (The Journal of Nutrition).',
      '• There are some interesting (albeit possibly misleading!) articles in Nature Medicine and other journals that suggested that getting the RSV vaccine and also the shingles vaccine could LOWER your risk of developing dementia. The theory is that some of the "adjuvant" ingredients in these vaccines, which help strengthen the immunity to RSV or shingles, may also help protect you from dementia. Although this data is very interesting and deserves further study, there are problems with it as well and it seems premature to draw a causal relationship between these vaccines and dementia. Sorry!',
      '• Unfortunately, there is bad news for the mRNA vaccines that were so critical in preventing deaths at the height of the COVID-19 pandemic: HHS has halted $500 million in vaccine development projects that all use mRNA technology. The vaccine projects being halted included COVID-19 and bird flu (H5N1).',
      'About Dr. Sujansky\'s Life in These Times',
      'My family spent a week in Ashland Oregon in July: rather than rushing around and trying to see as much as possible in little time (I will admit to this being our usual modus operandi), we just stayed in an Air BNB and took hikes, got a massage, and watched plays. It was perfect. I had forgotten how much fun it is to sleep in and eat out. Heaven!',
      'Last weekend, I spent the weekend in Sonoma with some old friends from my medical school days. All women; all in a similar time in our lives. It was great hanging out and comparing how each of us are dealing with life\'s challenges and supporting each other. The location was beautiful and the company even better. I hope all of you have such friends that can help you "fill up your tank" every so often!',
    ],
  },
];
